/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLOContentPlaceholderBlockElement extends HTMLStencilElement {
    'animation': boolean;
    'lineHeight': number;
    'lines': number;
    'margin': number;
    'randomSize': boolean;
    'rounded': boolean;
  }
  var HTMLOContentPlaceholderBlockElement: {
    prototype: HTMLOContentPlaceholderBlockElement;
    new (): HTMLOContentPlaceholderBlockElement;
  };
  interface HTMLElementTagNameMap {
    'o-content-placeholder-block': HTMLOContentPlaceholderBlockElement;
  }
  interface ElementTagNameMap {
    'o-content-placeholder-block': HTMLOContentPlaceholderBlockElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'o-content-placeholder-block': JSXElements.OContentPlaceholderBlockAttributes;
    }
  }
  namespace JSXElements {
    export interface OContentPlaceholderBlockAttributes extends HTMLAttributes {
      'animation'?: boolean;
      'lineHeight'?: number;
      'lines'?: number;
      'margin'?: number;
      'randomSize'?: boolean;
      'rounded'?: boolean;
    }
  }
}


declare global {
  interface HTMLOContentPlaceholderImgElement extends HTMLStencilElement {
    'animation': boolean;
    'format': 'circle' | 'square';
    'size': number;
  }
  var HTMLOContentPlaceholderImgElement: {
    prototype: HTMLOContentPlaceholderImgElement;
    new (): HTMLOContentPlaceholderImgElement;
  };
  interface HTMLElementTagNameMap {
    'o-content-placeholder-img': HTMLOContentPlaceholderImgElement;
  }
  interface ElementTagNameMap {
    'o-content-placeholder-img': HTMLOContentPlaceholderImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'o-content-placeholder-img': JSXElements.OContentPlaceholderImgAttributes;
    }
  }
  namespace JSXElements {
    export interface OContentPlaceholderImgAttributes extends HTMLAttributes {
      'animation'?: boolean;
      'format'?: 'circle' | 'square';
      'size'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
