/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  ContentPlaceholder as OContentPlaceholderHead
} from './components/o-content-placeholder-head/o-content-placeholder-head';

declare global {
  interface HTMLOContentPlaceholderHeadElement extends OContentPlaceholderHead, HTMLElement {
  }
  var HTMLOContentPlaceholderHeadElement: {
    prototype: HTMLOContentPlaceholderHeadElement;
    new (): HTMLOContentPlaceholderHeadElement;
  };
  interface HTMLElementTagNameMap {
    "o-content-placeholder-head": HTMLOContentPlaceholderHeadElement;
  }
  interface ElementTagNameMap {
    "o-content-placeholder-head": HTMLOContentPlaceholderHeadElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-content-placeholder-head": JSXElements.OContentPlaceholderHeadAttributes;
    }
  }
  namespace JSXElements {
    export interface OContentPlaceholderHeadAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}


import {
  ContentPlaceholderImg as OContentPlaceholderImg
} from './components/o-content-placeholder-img/o-content-placeholder-img';

declare global {
  interface HTMLOContentPlaceholderImgElement extends OContentPlaceholderImg, HTMLElement {
  }
  var HTMLOContentPlaceholderImgElement: {
    prototype: HTMLOContentPlaceholderImgElement;
    new (): HTMLOContentPlaceholderImgElement;
  };
  interface HTMLElementTagNameMap {
    "o-content-placeholder-img": HTMLOContentPlaceholderImgElement;
  }
  interface ElementTagNameMap {
    "o-content-placeholder-img": HTMLOContentPlaceholderImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-content-placeholder-img": JSXElements.OContentPlaceholderImgAttributes;
    }
  }
  namespace JSXElements {
    export interface OContentPlaceholderImgAttributes extends HTMLAttributes {
      animate?: boolean;
      format?: 'circle' | 'square';
      size?: number;
    }
  }
}


import {
  ContentPlaceholder as OContentPlaceholderText
} from './components/o-content-placeholder-text/o-content-placeholder-text';

declare global {
  interface HTMLOContentPlaceholderTextElement extends OContentPlaceholderText, HTMLElement {
  }
  var HTMLOContentPlaceholderTextElement: {
    prototype: HTMLOContentPlaceholderTextElement;
    new (): HTMLOContentPlaceholderTextElement;
  };
  interface HTMLElementTagNameMap {
    "o-content-placeholder-text": HTMLOContentPlaceholderTextElement;
  }
  interface ElementTagNameMap {
    "o-content-placeholder-text": HTMLOContentPlaceholderTextElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-content-placeholder-text": JSXElements.OContentPlaceholderTextAttributes;
    }
  }
  namespace JSXElements {
    export interface OContentPlaceholderTextAttributes extends HTMLAttributes {
      lines?: number;
    }
  }
}


import {
  ContentPlaceholder as OContentPlaceholder
} from './components/o-content-placeholder/o-content-placeholder';

declare global {
  interface HTMLOContentPlaceholderElement extends OContentPlaceholder, HTMLElement {
  }
  var HTMLOContentPlaceholderElement: {
    prototype: HTMLOContentPlaceholderElement;
    new (): HTMLOContentPlaceholderElement;
  };
  interface HTMLElementTagNameMap {
    "o-content-placeholder": HTMLOContentPlaceholderElement;
  }
  interface ElementTagNameMap {
    "o-content-placeholder": HTMLOContentPlaceholderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-content-placeholder": JSXElements.OContentPlaceholderAttributes;
    }
  }
  namespace JSXElements {
    export interface OContentPlaceholderAttributes extends HTMLAttributes {
      active?: boolean;
      animated?: boolean;
      centered?: boolean;
      rounded?: boolean;
    }
  }
}

